services:
  app:
    build: .
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
      - S3_ENDPOINT=minio
      - S3_PORT=9000
      - S3_SSL=false
      - S3_BUCKET=test-attributions
      - S3_ACCESS_KEY=minioadmin
      - S3_SECRET_KEY=minioadmin
